### ISSUE TITLE
Default constructor error

### ISSUE THREAD

**Issue by abiessener** [jershell/kbson#11]
Hi there --

Thanks for the lib.

I'm using kbson inside kMongo. That part works great.

Trying to use kbson to manually serialize/deserialize doesn't work, though. I can't even instantiate the class.

```
java.lang.NoSuchMethodError: com.github.jershell.kbson.Configuration.<init>(ZLjava/lang/String;ILkotlin/jvm/internal/DefaultConstructorMarker;)V

	at com.github.jershell.kbson.KBson.<init>(KBson.kt:12)
	at com.github.jershell.kbson.KBson.<clinit>(KBson.kt:41)
```

Not sure what to do here, honestly.

**Comment by jershell** [comment]
Hi, I can not reproduce it. Did you clear and rebuild your project?  What is a version?

**Comment by jbmolle** [comment]
Hi @abiessener
The problem comes from KMongo library.
KMongo forked this library and overwrote some files in the package. You can see the code on KMongo github, kmongo-kbson package.
In particular Configuration has 1 more variable in KMongo.
So when you're using KMongo and KBson together you have a problem with Configuration initializer. Java methods don't have the same signature.

**Comment by jershell** [comment]
@zigzago Hi, can you help us with this story, I have no idea what to do in this situation?

**Comment by zigzago** [comment]
The fork was not intended to stay. I need to investigate the diff between the two code bases, send other PRs to kbson and then remove the kmongo kbson fork. I've created an issue to follow this work: https://github.com/Litote/kmongo/issues/173

As a workaround, use only kbson kmongo fork when kmongo is present in your classpath.

**Comment by lamba92** [comment]
Having the same issue, but the artifact is present and loaded in the classpath. IntelliJ correctly sees it and let me navigate the code until `Configuration`. I'll investigate.
